# Generated by Django 5.2.12 on 2026-03-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='reported_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
