import argparse
import os
import re
import sqlite3
import sys
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql


ROOT = Path(__file__).resolve().parents[1]
DJANGO_ROOT = ROOT / "be"
SQLITE_DEFAULT = ROOT / "kbo_stats.db"
sys.path.insert(0, str(DJANGO_ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django  # noqa: E402

django.setup()

from django.conf import settings  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migrate SQLite data to PostgreSQL.")
    parser.add_argument("--sqlite", default=str(SQLITE_DEFAULT), help="Source SQLite DB path")
    parser.add_argument("--batch-size", type=int, default=1000, help="Insert batch size")
    parser.add_argument("--drop-existing", action="store_true", help="Drop existing PostgreSQL tables before creating them")
    return parser.parse_args()


def quote_ident(name: str) -> sql.Identifier:
    return sql.Identifier(name)


def pg_name(name: str) -> str:
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        return name.lower()
    return name


def sqlite_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type='table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    return [row[0] for row in rows]


def table_info(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    rows = conn.execute(f'PRAGMA table_info("{table}")').fetchall()
    return [
        {
            "cid": row[0],
            "name": row[1],
            "pg_name": pg_name(row[1]),
            "type": row[2] or "",
            "notnull": bool(row[3]),
            "default": row[4],
            "pk": int(row[5]),
        }
        for row in rows
    ]


def unique_indexes(conn: sqlite3.Connection, table: str) -> list[list[str]]:
    out: list[list[str]] = []
    for row in conn.execute(f'PRAGMA index_list("{table}")').fetchall():
        _, index_name, is_unique, origin, _ = row
        if not is_unique or origin == "pk":
            continue
        cols = conn.execute(f'PRAGMA index_info("{index_name}")').fetchall()
        out.append([col[2] for col in cols])
    return out


def map_sqlite_type(sqlite_type: str) -> str:
    upper = sqlite_type.upper()
    if "INT" in upper:
        return "BIGINT"
    if any(token in upper for token in ("REAL", "DOUBLE", "FLOAT")):
        return "NUMERIC"
    if "BOOL" in upper:
        return "BOOLEAN"
    if upper.startswith("VARCHAR") or upper.startswith("CHAR"):
        return upper
    if "DATETIME" in upper or "TIMESTAMP" in upper:
        return "TIMESTAMP"
    if upper == "DATE":
        return "DATE"
    return "TEXT"


def normalize_default(value: str | None, pg_type: str) -> sql.SQL | None:
    if value is None:
        return None
    raw = value.strip()
    if not raw:
        return None
    upper_type = pg_type.upper()
    if upper_type == "BOOLEAN":
        if raw in {"0", "FALSE", "false"}:
            return sql.SQL("DEFAULT FALSE")
        if raw in {"1", "TRUE", "true"}:
            return sql.SQL("DEFAULT TRUE")
    return sql.SQL(f"DEFAULT {raw}")


def create_table(pg_conn: psycopg.Connection, sqlite_conn: sqlite3.Connection, table: str, drop_existing: bool) -> list[dict[str, Any]]:
    columns = table_info(sqlite_conn, table)
    uniques = unique_indexes(sqlite_conn, table)
    pk_columns = [col["pg_name"] for col in sorted(columns, key=lambda item: item["pk"]) if col["pk"] > 0]

    statements: list[sql.SQL] = []
    single_identity_pk = (
        len(pk_columns) == 1
        and next(col for col in columns if col["pg_name"] == pk_columns[0])["type"].upper().find("INT") >= 0
    )

    for col in columns:
        parts: list[sql.Composable] = [quote_ident(col["pg_name"])]
        pg_type = map_sqlite_type(col["type"])
        is_identity_pk = single_identity_pk and col["pg_name"] == pk_columns[0]
        if is_identity_pk:
            parts.append(sql.SQL("BIGINT GENERATED BY DEFAULT AS IDENTITY"))
        else:
            parts.append(sql.SQL(pg_type))

        default_sql = None if is_identity_pk else normalize_default(col["default"], pg_type)
        if default_sql is not None:
            parts.append(default_sql)
        if col["notnull"] or is_identity_pk:
            parts.append(sql.SQL("NOT NULL"))
        statements.append(sql.SQL(" ").join(parts))

    table_constraints: list[sql.SQL] = []
    if pk_columns:
        table_constraints.append(
            sql.SQL("PRIMARY KEY ({})").format(
                sql.SQL(", ").join(quote_ident(col) for col in pk_columns)
            )
        )

    for idx, cols in enumerate(uniques, start=1):
        table_constraints.append(
            sql.SQL("CONSTRAINT {} UNIQUE ({})").format(
                quote_ident(f"{table}_uniq_{idx}"),
                sql.SQL(", ").join(quote_ident(pg_name(col)) for col in cols),
            )
        )

    all_defs = statements + table_constraints
    create_sql = sql.SQL("CREATE TABLE {} ({})").format(
        quote_ident(table),
        sql.SQL(", ").join(all_defs),
    )

    with pg_conn.cursor() as cur:
        if drop_existing:
            cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(quote_ident(table)))
        cur.execute(create_sql)
    pg_conn.commit()
    return columns


def transform_row(row: tuple[Any, ...], columns: list[dict[str, Any]]) -> tuple[Any, ...]:
    out: list[Any] = []
    for value, col in zip(row, columns):
        pg_type = map_sqlite_type(col["type"])
        if value is None:
            out.append(None)
        elif pg_type == "BOOLEAN":
            out.append(bool(value))
        else:
            out.append(value)
    return tuple(out)


def copy_table(
    pg_conn: psycopg.Connection,
    sqlite_conn: sqlite3.Connection,
    table: str,
    columns: list[dict[str, Any]],
    batch_size: int,
) -> int:
    column_names = [col["pg_name"] for col in columns]
    insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
        quote_ident(table),
        sql.SQL(", ").join(quote_ident(col) for col in column_names),
        sql.SQL(", ").join(sql.Placeholder() for _ in column_names),
    )

    total = 0
    cursor = sqlite_conn.execute(f'SELECT * FROM "{table}"')
    with pg_conn.cursor() as cur:
        while True:
            batch = cursor.fetchmany(batch_size)
            if not batch:
                break
            rows = [transform_row(row, columns) for row in batch]
            cur.executemany(insert_sql, rows)
            total += len(rows)
        pg_conn.commit()
    return total


def reset_identity(pg_conn: psycopg.Connection, table: str, columns: list[dict[str, Any]]) -> None:
    pk_columns = [col for col in columns if col["pk"] > 0]
    if len(pk_columns) != 1 or "INT" not in pk_columns[0]["type"].upper():
        return
    pk_name = pk_columns[0]["pg_name"]
    with pg_conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                SELECT setval(
                    pg_get_serial_sequence(%s, %s),
                    COALESCE((SELECT MAX({pk}) FROM {table}), 1),
                    (SELECT COUNT(*) > 0 FROM {table})
                )
                """
            ).format(
                pk=quote_ident(pk_name),
                table=quote_ident(table),
            ),
            (table, pk_name),
        )
    pg_conn.commit()


def postgres_connect() -> psycopg.Connection:
    db = settings.DATABASES["default"]
    if db["ENGINE"] != "django.db.backends.postgresql":
        raise SystemExit("Current Django database is not PostgreSQL. Check kbo_stat_BE/be/.env first.")
    return psycopg.connect(
        dbname=db["NAME"],
        user=db["USER"],
        password=db["PASSWORD"],
        host=db["HOST"],
        port=db["PORT"],
    )


def main() -> None:
    args = parse_args()
    sqlite_path = Path(args.sqlite)
    if not sqlite_path.exists():
        raise SystemExit(f"Missing SQLite DB: {sqlite_path}")

    sqlite_conn = sqlite3.connect(str(sqlite_path))
    pg_conn = postgres_connect()
    try:
        tables = sqlite_tables(sqlite_conn)
        print(f"Found {len(tables)} SQLite tables")
        for table in tables:
            columns = create_table(pg_conn, sqlite_conn, table, drop_existing=args.drop_existing)
            count = copy_table(pg_conn, sqlite_conn, table, columns, args.batch_size)
            reset_identity(pg_conn, table, columns)
            print(f"[ok] {table}: {count} rows")
    finally:
        sqlite_conn.close()
        pg_conn.close()


if __name__ == "__main__":
    main()
